<?php
class WC_Gateway_Skye_Online_Street_Type {

    /**
     * Instance of this class.
     *
     * @access protected
     * @access static
     * @var object
     */
    protected static $instance = null;

    private static $STREET_TYPES = [
        'ave' => 'avenue',
        'acc' => 'access',
        'al' => 'alley',
        'awy' => 'alleyway',
        'amb' => 'amble',
        'anc' => 'anchorage',
        'app' => 'approach',
        'arc' => 'arcade',
        'art' => 'artery',
        'bk' => 'bank',
        'bas' => 'basin',
        'by' => 'bay',
        'bch' => 'beach',
        'bt' => 'belt',
        'bnd' => 'bend',
        'blk' => 'block',
        'blv' => 'boulevard',
        'br' => 'brace',
        'bra' => 'brae',
        'brk' => 'break',
        'bs' => 'briars',
        'brg' => 'bridge',
        'bwy' => 'broadway',
        'brw' => 'brow',
        'bps' => 'bypass',
        'byw' => 'byway',
        'cwy' => 'causeway',
        'ctr' => 'centre',
        'cnwy' => 'centreway',
        'ch' => 'chase',
        'cir' => 'circle',
        'clt' => 'circlet',
        'cct' => 'circuit',
        'crc' => 'circus',
        'cl' => 'close',
        'cld' => 'colonnade',
        'cmn' => 'common',
        'cnc' => 'concourse',
        'cps' => 'copse',
        'cnr' => 'corner',
        'cso' => 'corso',
        'crse' => 'course',
        'ct' => 'court',
        'cts' => 'courts',
        'cyd' => 'courtyard',
        'cve' => 'cove',
        'crs' => 'crescent',
        'cs' => 'crest',
        'crft' => 'croft',
        'crss' => 'cross',
        'csg' => 'crossing',
        'crd' => 'crossroad',
        'crw' => 'crossway',
        'csw' => 'cruiseway',
        'cds' => 'cul-de-sac',
        'cut' => 'cutting',
        'dal' => 'dale',
        'dl' => 'dell',
        'dvn' => 'deviation',
        'dip' => 'dip',
        'dtr' => 'distributor',
        'dn' => 'downs',
        'dr' => 'drive',
        'dry' => 'driveway',
        'ea' => 'east',
        'ege' => 'edge',
        'elb' => 'elbow',
        'elm' => 'elm',
        'ed' => 'end',
        'ent' => 'entrance',
        'esp' => 'esplanade',
        'est' => 'estate',
        'exp' => 'expressway',
        'extn' => 'extension',
        'fay' => 'fairway',
        'ftk' => 'fire track',
        'ftl' => 'firetrail',
        'flt' => 'flat',
        'flats' => 'flats',
        'flw' => 'follow',
        'ftw' => 'footway',
        'fsr' => 'foreshore',
        'fmn' => 'formation',
        'fwy' => 'freeway',
        'frt' => 'front',
        'fr' => 'frontage',
        'gap' => 'gap',
        'gdn' => 'garden',
        'gds' => 'gardens',
        'gte' => 'gate',
        'gts' => 'gates',
        'gl' => 'glade',
        'gln' => 'glen',
        'gra' => 'grange',
        'ge' => 'great',
        'grn' => 'green',
        'grd' => 'ground',
        'gve' => 'grove',
        'gly' => 'gully',
        'havn' => 'haven',
        'head' => 'head',
        'hth' => 'heath',
        'hts' => 'heights',
        'hrd' => 'highroad',
        'hwy' => 'highway',
        'hl' => 'hill',
        'hub' => 'hub',
        'itc' => 'interchange',
        'its' => 'intersection',
        'is' => 'island',
        'jn' => 'junction',
        'key' => 'key',
        'ldg' => 'landing',
        'la' => 'lane',
        'lwy' => 'laneway',
        'largo' => 'largo',
        'lee' => 'lees',
        'li' => 'line',
        'lk' => 'link',
        'lt' => 'little',
        'loch' => 'loch',
        'lkt' => 'lookout',
        'lp' => 'loop',
        'lwr' => 'lower',
        'ma' => 'mall',
        'md' => 'mead',
        'mw' => 'meadows',
        'mdr' => 'meander',
        'mew' => 'mew',
        'mws' => 'mews',
        'ml' => 'mile',
        'mwy' => 'motorway',
        'mt' => 'mount',
        'nk' => 'nook',
        'out' => 'outlook',
        'pde' => 'parade',
        'pk' => 'park',
        'pkld' => 'parklands',
        'pwy' => 'parkway',
        'prt' => 'part',
        'pss' => 'pass',
        'pth' => 'path',
        'phwy' => 'pathway',
        'pza' => 'piazza',
        'pl' => 'place',
        'plat' => 'plateau',
        'plz' => 'plaza',
        'pkt' => 'pocket',
        'pnt' => 'point',
        'pts' => 'points',
        'pt' => 'port',
        'prm' => 'promenade',
        'purs' => 'pursuit',
        'qud' => 'quad',
        'qdg' => 'quadrangle',
        'qd' => 'quadrant',
        'qy' => 'quay',
        'qys' => 'quays',
        'ra' => 'ramble',
        'rmp' => 'ramp',
        'rge' => 'range',
        'rch' => 'reach',
        'res' => 'reserve',
        'rst' => 'rest',
        'ret' => 'ret',
        'rt' => 'retreat',
        'retn' => 'return',
        'rid' => 'ride',
        'rdg' => 'ridge',
        'rdw' => 'ridgeway',
        'rtw' => 'right of way',
        'rng' => 'ring',
        'ri' => 'rise',
        'rvr' => 'river',
        'rvw' => 'riverway',
        'rva' => 'riviera',
        'rd' => 'road',
        'rds' => 'roads',
        'rsd' => 'roadside',
        'rdy' => 'roadway',
        'rde' => 'ronde',
        'rbl' => 'rosebowl',
        'rty' => 'rotary',
        'rnd' => 'round',
        'rte' => 'route',
        'row' => 'row',
        'rue' => 'rue',
        'run' => 'run',
        'swy' => 'service way',
        'shop' => 'shopping centre',
        'sdg' => 'siding',
        'slp' => 'slope',
        'snd' => 'sound',
        'spr' => 'spur',
        'sq' => 'square',
        'sta' => 'stairs',
        'shw' => 'state highway',
        'stp' => 'steps',
        'strait' => 'strait',
        'stra' => 'strand',
        'st' => 'street',
        'sp' => 'strip',
        'sy' => 'subway',
        'smmt' => 'summit',
        'ta' => 'tailings',
        'tarn' => 'tarn',
        'tce' => 'terrace',
        'thf' => 'thoroughfare',
        'twy' => 'tollway',
        'top' => 'top',
        'tor' => 'tor',
        'twr' => 'towers',
        'tr' => 'track',
        'trl' => 'trail',
        'trr' => 'trailer',
        'ty' => 'tramway',
        'tri' => 'triangle',
        'tkw' => 'trunkway',
        'tn' => 'tunnel',
        'tur' => 'turn',
        'unp' => 'underpass',
        'upr' => 'upper',
        'val' => 'vale',
        'vy' => 'valley',
        'vdt' => 'viaduct',
        'vw' => 'view',
        've' => 'village',
        'vlls' => 'villas',
        'vst' => 'vista',
        'wd' => 'wade',
        'wk' => 'walk',
        'wky' => 'walkway',
        'waters' => 'waters',
        'way' => 'way',
        'wt' => 'west',
        'wf' => 'wharf',
        'wood' => 'wood',
        'wnd' => 'wynd',
        'yrd' => 'yard',
    ];

    /**
     * Return an instance of this class.
     *
     * @return object A single instance of this class.
     */
    public static function get_instance() {
      // If the single instance hasn't been set, set it now.
      if( null == self::$instance ) {
        self::$instance = new self;
      }

      return self::$instance;
    }

    /**
     * Fix the street type (SKYE is very sensitive)
     * @param  String $street_type
     * @return String
     */
    public function parse($street_type) {
      $street_type = strtolower($street_type);
      if (isset(self::$STREET_TYPES[$street_type])) {
          return ucwords($street_type);
      }
      $key = array_search($street_type, self::$STREET_TYPES);
      if ($key) {
        return ucwords($key);
      }
      return null;
    }

}
